export interface Service {
  slug: string;
  title: string;
  shortDescription: string;
  description: string;
  category: "clinica" | "estetica" | "laser" | "tricologia" | "unas";
  categoryLabel: string;
  duration?: string;
  sessions?: string;
  priceRange?: string;
  candidates: string[];
  process: string[];
  aftercare: string[];
  faq: { q: string; a: string }[];
  relatedServices: string[];
  keywords: string[];
}

export const services: Service[] = [
  {
    slug: "acne",
    title: "Tratamiento del Acné",
    shortDescription: "Diagnóstico y tratamiento personalizado para acné leve, moderado y severo con enfoque médico y resultados duraderos.",
    description: "El acné es la afección dermatológica más frecuente, pero su manejo requiere un diagnóstico preciso para identificar el tipo de acné, los factores desencadenantes y el plan de tratamiento adecuado. La Dra. Téllez ofrece tratamientos personalizados que van desde terapia tópica y sistémica hasta procedimientos en consultorio como peeling químico, fotodinámica y extracción profesional.",
    category: "clinica",
    categoryLabel: "Dermatología Clínica",
    duration: "30-45 minutos por sesión",
    sessions: "Según el tipo y severidad del acné",
    priceRange: "Desde $280.000 COP",
    candidates: [
      "Personas con acné activo (comedones, pápulas, pústulas, quistes)",
      "Pacientes con cicatrices de acné previas",
      "Quienes han probado múltiples tratamientos sin éxito",
      "Adultos con acné hormonal",
      "Adolescentes con acné moderado a severo",
    ],
    process: [
      "Consulta inicial: evaluación clínica y dermatoscópica de las lesiones",
      "Diagnóstico del tipo de acné y factores asociados",
      "Diseño del plan de tratamiento personalizado",
      "Tratamiento tópico y/o sistémico según indicación",
      "Procedimientos en consultorio si se requieren",
      "Seguimiento y ajuste del tratamiento",
    ],
    aftercare: [
      "Usar únicamente los productos indicados por la Dra. Téllez",
      "Protección solar diaria (SPF 30+)",
      "No manipular ni exprimir las lesiones",
      "Mantener la rutina de limpieza facial indicada",
      "Asistir a los controles programados",
    ],
    faq: [
      { q: "¿Cuánto tiempo tarda el tratamiento del acné en hacer efecto?", a: "Los primeros resultados suelen observarse entre las 4 y 8 semanas de iniciado el tratamiento. El control completo puede tomar de 3 a 6 meses, dependiendo del tipo y severidad del acné." },
      { q: "¿El acné en adultos se trata igual que el de los adolescentes?", a: "No. El acné adulto, especialmente en mujeres, frecuentemente tiene un componente hormonal que requiere un abordaje diferente. La Dra. Téllez evalúa cada caso de forma individual." },
      { q: "¿El tratamiento con isotretinoína (Roaccutan) es seguro?", a: "La isotretinoína es el tratamiento más efectivo para el acné severo. Con el seguimiento adecuado de la Dra. Téllez, es segura. Requiere controles regulares y medidas anticonceptivas en mujeres en edad fértil." },
    ],
    relatedServices: ["peeling-quimico", "laser-co2", "cosmelan"],
    keywords: ["tratamiento acné bogotá", "dermatologa acné bogotá", "acné severo bogotá", "cicatrices acné bogotá"],
  },
  {
    slug: "toxina-botulinica",
    title: "Toxina Botulínica",
    shortDescription: "Botox para suavizar líneas de expresión, arrugas y lograr un rejuvenecimiento facial natural. Dra. Téllez es vocera oficial Abbott.",
    description: "La toxina botulínica (botox) es el tratamiento estético más solicitado del mundo. La Dra. Téllez, vocera oficial de Abbott, aplica la toxina con técnica precisa para suavizar líneas de expresión en frente, entrecejo y patas de gallo, con resultados naturales que preservan la expresividad del rostro. También se usa para el botox preventivo, el lifting de cejas y la hiperhidrosis.",
    category: "estetica",
    categoryLabel: "Dermatología Estética",
    duration: "30–45 minutos",
    sessions: "1 sesión · efecto en 7–14 días",
    priceRange: "Desde $1.100.000 COP",
    candidates: [
      "Adultos con líneas de expresión en frente, entrecejo o patas de gallo",
      "Personas que buscan un rejuvenecimiento facial natural y sutil",
      "Pacientes que desean botox preventivo desde los 25–30 años",
      "Quienes buscan lifting no quirúrgico de cejas",
      "Pacientes con hiperhidrosis (sudoración excesiva) en axilas o manos",
    ],
    process: [
      "Consulta de evaluación facial y análisis de proporciones",
      "Diseño del plan de aplicación según los objetivos del paciente",
      "Limpieza de la zona y marcación de puntos de aplicación",
      "Aplicación de la toxina con microcánula o aguja fina",
      "Evaluación inmediata post-procedimiento",
      "Control a las 2 semanas para valorar resultado y ajustes",
    ],
    aftercare: [
      "No tocar, frotar ni masajear la zona tratada las primeras 4 horas",
      "No acostarse ni agacharse en las 4 horas siguientes",
      "Evitar ejercicio físico intenso el día del procedimiento",
      "No exponerse al sol directo ni al calor excesivo las primeras 24 horas",
      "Dormir boca arriba la primera noche",
    ],
    faq: [
      { q: "¿Cuánto dura el efecto de la toxina botulínica?", a: "El efecto dura entre 4 y 6 meses. Con tratamientos regulares y continuos, el músculo se reacondiciona y el efecto tiende a prolongarse con el tiempo." },
      { q: "¿A qué edad es recomendable empezar con botox preventivo?", a: "El botox preventivo puede considerarse desde los 25–30 años, cuando empiezan a formarse las primeras líneas dinámicas. La Dra. Téllez evalúa cada caso individualmente." },
      { q: "¿El botox se ve natural?", a: "En manos expertas, sí. La Dra. Téllez prioriza resultados que preserven la expresividad y armonía del rostro, evitando el efecto 'congelado'." },
    ],
    relatedServices: ["acido-hialuronico", "sculptra", "peeling-quimico"],
    keywords: ["botox bogotá", "toxina botulínica bogotá", "botox preventivo bogotá", "rejuvenecimiento facial bogotá"],
  },
  {
    slug: "acido-hialuronico",
    title: "Ácido Hialurónico",
    shortDescription: "Fillers de ácido hialurónico para labios, ojeras, pómulos y rinomodelación. Resultados naturales y reversibles. Vocera Abbott.",
    description: "El ácido hialurónico es un filler biodegradable y reversible que permite restaurar volumen, definir contornos y rejuvenecer el rostro de forma natural. La Dra. Téllez, vocera oficial de Abbott, trabaja con los productos de mayor seguridad y durabilidad del mercado. Sus técnicas incluyen aumento de labios, filler de ojeras (valle lagrimal), proyección de pómulos y rinomodelación sin cirugía.",
    category: "estetica",
    categoryLabel: "Dermatología Estética",
    duration: "30–60 minutos",
    sessions: "1 sesión · resultado inmediato",
    priceRange: "Desde $1.100.000 COP por jeringa",
    candidates: [
      "Personas que desean aumentar o definir los labios",
      "Pacientes con ojeras profundas o surco nasoyugal marcado",
      "Quienes buscan proyección y volumen en los pómulos",
      "Pacientes que desean corregir la nariz sin cirugía (rinomodelación)",
      "Personas con pérdida de volumen facial por envejecimiento",
    ],
    process: [
      "Consulta de evaluación facial y definición de los objetivos estéticos",
      "Aplicación de anestesia tópica en zonas sensibles (labios, ojeras)",
      "Inyección del ácido hialurónico con técnica de microcánula o aguja fina",
      "Modelado suave de la zona tratada",
      "Evaluación inmediata del resultado",
      "Control a las 2 semanas para valorar el resultado definitivo",
    ],
    aftercare: [
      "No masajear la zona tratada las primeras 24 horas",
      "Aplicar hielo envuelto en un paño si hay inflamación (nunca directo sobre la piel)",
      "Evitar besos fuertes o movimientos exagerados de labios las primeras 24 horas",
      "No exponerse al calor excesivo (sauna, sol) las primeras 48 horas",
      "El resultado definitivo se aprecia a las 2 semanas, cuando cede la inflamación",
    ],
    faq: [
      { q: "¿El ácido hialurónico es reversible?", a: "Sí. Una de sus principales ventajas es que puede disolverse completamente con hialuronidasa si el paciente no está conforme con el resultado o desea retirarlo." },
      { q: "¿Cuánto tiempo dura el ácido hialurónico?", a: "Depende de la zona: en labios dura entre 6 y 12 meses; en ojeras entre 12 y 18 meses; en pómulos entre 12 y 24 meses. La Dra. Téllez lo indica según cada caso." },
      { q: "¿Duele el filler de ácido hialurónico?", a: "Se aplica anestesia tópica antes del procedimiento. La mayoría de los pacientes describe una leve sensación de presión, especialmente en los labios. El proceso es rápido y bien tolerado." },
    ],
    relatedServices: ["toxina-botulinica", "sculptra", "peeling-quimico"],
    keywords: ["ácido hialurónico bogotá", "filler labios bogotá", "ojeras bogotá", "rinomodelación bogotá", "fillers bogotá"],
  },
  {
    slug: "laser-co2",
    title: "Láser CO2",
    shortDescription: "Resurfacing profundo para cicatrices de acné, manchas, poros y rejuvenecimiento. Tecnología de última generación.",
    description: "El láser CO2 fraccionado es uno de los tratamientos más efectivos para el rejuvenecimiento cutáneo y la corrección de cicatrices de acné. Trabaja creando microcolumnas de ablación que estimulan la producción de colágeno y la regeneración de la piel, con resultados significativos visibles desde la primera sesión.",
    category: "laser",
    categoryLabel: "Tecnología Láser",
    duration: "60-90 minutos",
    sessions: "1-3 sesiones según el objetivo",
    priceRange: "Desde $1.500.000 COP por sesión",
    candidates: [
      "Pacientes con cicatrices de acné (atróficas o hipertróficas)",
      "Personas con manchas solares o hiperpigmentación",
      "Quienes desean mejorar la textura y tono de la piel",
      "Pacientes con poros dilatados",
      "Pieles con daño solar acumulado",
    ],
    process: [
      "Consulta y evaluación del tipo de piel y condición a tratar",
      "Aplicación de anestesia tópica (30-45 minutos antes)",
      "Calibración del equipo según el objetivo del tratamiento",
      "Aplicación del láser fraccionado",
      "Cuidados post-procedimiento inmediatos",
      "Control a los 7-10 días",
    ],
    aftercare: [
      "Aplicar la crema cicatrizante indicada cada 4-6 horas",
      "Protección solar rigurosa (SPF 50+ mínimo)",
      "No rascarse ni manipular las costras que puedan formarse",
      "Evitar el sol directo durante 4-6 semanas",
      "Hidratación intensa de la piel",
    ],
    faq: [
      { q: "¿Cuánto tiempo de recuperación requiere el láser CO2?", a: "El periodo de recuperación es de 5 a 10 días, durante los cuales la piel puede presentar enrojecimiento y descamación. La Dra. Téllez proporciona el protocolo de cuidado completo." },
      { q: "¿El láser CO2 funciona en todos los fototipos de piel?", a: "El láser CO2 requiere una evaluación cuidadosa en pieles morenas o de fototipo alto (IV-VI) para evitar hiperpigmentación post-inflamatoria. La Dra. Téllez ajusta los parámetros para cada paciente." },
      { q: "¿Cuántas sesiones necesito para mejorar las cicatrices de acné?", a: "Generalmente se recomiendan 1 a 3 sesiones espaciadas 3-6 meses. Los resultados más significativos se ven entre los 3 y 6 meses post-tratamiento." },
    ],
    relatedServices: ["acne", "peeling-quimico", "cosmelan"],
    keywords: ["láser CO2 bogotá", "resurfacing bogotá", "cicatrices acné láser bogotá", "rejuvenecimiento láser bogotá"],
  },
  {
    slug: "alopecia",
    title: "Tricología y Alopecia",
    shortDescription: "Diagnóstico y tratamiento integral de la caída del pelo, alopecia androgenética y areata. Enfoque médico y personalizado.",
    description: "La tricología es la subespecialidad dermatológica dedicada al diagnóstico y tratamiento de las enfermedades del cuero cabelludo y el pelo. La Dra. Téllez ofrece un enfoque integral que incluye evaluación clínica, tricoscopia (dermatoscopia capilar), análisis del patrón de pérdida y tratamientos tanto farmacológicos como procedimentales.",
    category: "tricologia",
    categoryLabel: "Tricología",
    duration: "30-45 minutos",
    sessions: "Seguimiento cada 3-6 meses",
    priceRange: "Desde $300.000 COP",
    candidates: [
      "Personas con caída excesiva de pelo (>100 pelos/día)",
      "Hombres y mujeres con alopecia androgenética (entradas, coronilla)",
      "Pacientes con alopecia areata (pérdida en parches)",
      "Quienes presentan pérdida post-parto (effluvio telógeno)",
      "Personas con cuero cabelludo con descamación o inflamación",
    ],
    process: [
      "Anamnesis completa: historia familiar, medicamentos, dieta, estrés",
      "Evaluación clínica y tricoscópica del cuero cabelludo",
      "Laboratorios complementarios si se requieren (hierro, tiroides, hormonas)",
      "Diagnóstico del tipo de alopecia",
      "Plan de tratamiento personalizado",
      "Controles fotográficos para evaluar la respuesta al tratamiento",
    ],
    aftercare: [
      "Seguir el esquema de tratamiento indicado con constancia",
      "Evitar productos agresivos sin consultar a la Dra. Téllez",
      "Mantener una alimentación equilibrada rica en proteínas y hierro",
      "No suspender el tratamiento sin consultar, incluso si mejora",
      "Reportar cualquier cambio en el patrón de caída",
    ],
    faq: [
      { q: "¿La alopecia androgenética tiene cura?", a: "La alopecia androgenética no tiene cura definitiva, pero sí un tratamiento efectivo que detiene su progresión y puede lograr regrowth. El tratamiento debe mantenerse para conservar los resultados." },
      { q: "¿Cuál es la diferencia entre effluvio y alopecia?", a: "El effluvio telógeno es una pérdida difusa y generalmente temporal, relacionada con estrés, dieta o enfermedad. La alopecia androgenética es un patrón progresivo de origen genético-hormonal. El diagnóstico diferencial es clave." },
      { q: "¿Qué son los exosomas y para qué sirven en tricología?", a: "Los exosomas son vesículas extracelulares cargadas de factores de crecimiento y señales regenerativas. En tricología, se aplican directamente en el cuero cabelludo para estimular los folículos pilosos, mejorar la densidad del pelo y frenar la caída. Son una de las terapias más innovadoras actualmente disponibles, con excelentes resultados especialmente en alopecia androgenética y effluvio." },
      { q: "¿En qué consiste la mesoterapia capilar?", a: "La mesoterapia capilar consiste en la aplicación de microinyecciones en el cuero cabelludo con una mezcla de vitaminas, minerales, aminoácidos y activos estimulantes del folículo piloso. Mejora la circulación local, nutre los folículos y reduce la caída del pelo. Es un tratamiento mínimamente invasivo, sin tiempo de recuperación, que se realiza en sesiones espaciadas y se complementa con el tratamiento médico de base." },
    ],
    relatedServices: ["mesoterapia-capilar", "toxina-botulinica"],
    keywords: ["alopecia bogotá", "caída del pelo bogotá", "tricología bogotá", "mesoterapia capilar bogotá"],
  },
  {
    slug: "mesoterapia-capilar",
    title: "Mesoterapia Capilar y Dermapeel",
    shortDescription: "Tratamiento intensivo para la caída del pelo que combina mesoterapia capilar con Dermapeel: microinyecciones de activos nutritivos más microagujación para máxima absorción y estimulación folicular.",
    description: "La mesoterapia capilar con Dermapeel es uno de los tratamientos más completos para la caída del pelo y la salud del cuero cabelludo. Combina microinyecciones con un cóctel de vitaminas, minerales, aminoácidos y factores de crecimiento, potenciada con Dermapeel — técnica de microagujación que crea microcanales en el cuero cabelludo para maximizar la absorción de los activos y estimular directamente los folículos pilosos.",
    category: "tricologia",
    categoryLabel: "Tricología",
    duration: "45–60 minutos",
    sessions: "4–6 sesiones iniciales · mantenimiento mensual",
    priceRange: "Desde $450.000 COP por sesión",
    candidates: [
      "Personas con caída difusa o excesiva de pelo",
      "Pacientes con alopecia androgenética en etapas tempranas o moderadas",
      "Quienes buscan fortalecer y engrosar el pelo debilitado o fino",
      "Pacientes con cuero cabelludo seco, con caspa o con mala circulación",
      "Como complemento al tratamiento médico de la alopecia",
      "Personas que buscan una alternativa no invasiva",
    ],
    process: [
      "Evaluación tricoscópica del cuero cabelludo y del patrón de pérdida de pelo",
      "Selección del cóctel de activos según el diagnóstico (vitaminas del complejo B, biotina, zinc, aminoácidos, péptidos)",
      "Limpieza del cuero cabelludo",
      "Aplicación del Dermapeel: microagujación controlada para crear canales de absorción",
      "Infiltración del cóctel mesoterapéutico en las zonas de mayor pérdida",
      "Masaje de cierre para favorecer la distribución de los activos",
    ],
    aftercare: [
      "No lavar el pelo las primeras 12–24 horas tras la sesión",
      "Evitar exposición solar directa en el cuero cabelludo durante 48 horas",
      "No aplicar productos químicos (tinte, permanente) por al menos 1 semana",
      "Evitar el ejercicio intenso el día del procedimiento",
      "Mantener el tratamiento médico de base indicado por la Dra. Téllez",
      "Es normal sentir leve sensibilidad o enrojecimiento las primeras horas",
    ],
    faq: [
      { q: "¿Cuándo se empiezan a ver resultados con la mesoterapia capilar?", a: "La mayoría de los pacientes nota reducción de la caída entre la 2ª y 3ª sesión. La mejora en grosor y densidad del pelo se aprecia de forma más evidente a partir de los 2–3 meses de tratamiento." },
      { q: "¿Qué es el Dermapeel y qué lo diferencia de la mesoterapia tradicional?", a: "El Dermapeel es una técnica de microagujación del cuero cabelludo que crea microcanales superficiales, permitiendo que los activos de la mesoterapia penetren de forma mucho más profunda y eficaz. Además, el estímulo mecánico activa por sí solo la regeneración folicular. La combinación de ambas técnicas potencia significativamente los resultados." },
      { q: "¿La mesoterapia capilar con Dermapeel duele?", a: "La sensación es leve. La microagujación puede generar una ligera picazón o calor en el cuero cabelludo durante el procedimiento, pero es bien tolerada por la mayoría de los pacientes. No requiere anestesia." },
    ],
    relatedServices: ["alopecia", "depilacion-laser"],
    keywords: ["mesoterapia capilar bogotá", "dermapeel bogotá", "tratamiento caída pelo bogotá", "microagujación cuero cabelludo bogotá"],
  },
  {
    slug: "peeling-quimico",
    title: "Peeling Químico",
    shortDescription: "Renovación celular para manchas, poros, cicatrices y acné activo. Tratamientos con ácidos de diferentes profundidades.",
    description: "El peeling químico es un tratamiento que utiliza ácidos para acelerar la renovación celular de la piel. La Dra. Téllez selecciona el tipo de peeling (superficial, medio o profundo) y la formulación adecuada según las necesidades de cada paciente, garantizando resultados seguros y efectivos.",
    category: "estetica",
    categoryLabel: "Dermatología Estética",
    duration: "30-60 minutos",
    sessions: "3-6 sesiones espaciadas 2-4 semanas",
    priceRange: "Desde $350.000 COP por sesión",
    candidates: [
      "Personas con manchas solares o melasma",
      "Pacientes con acné activo y cicatrices superficiales",
      "Pieles con textura irregular o poros dilatados",
      "Pacientes que buscan luminosidad y renovación cutánea",
      "Pieles con daño solar leve a moderado",
    ],
    process: [
      "Evaluación del tipo y condición de la piel",
      "Selección del ácido y profundidad adecuados",
      "Preparación previa de la piel (pre-peeling, 2-4 semanas antes)",
      "Aplicación del peeling en consultorio",
      "Instrucciones post-procedimiento detalladas",
      "Seguimiento y evaluación de resultados",
    ],
    aftercare: [
      "Aplicar hidratante y cicatrizante según las indicaciones",
      "Protección solar rigurosa (SPF 50+) durante todo el tratamiento",
      "No exfoliar la piel durante la fase de recuperación",
      "Evitar el calor excesivo y el ejercicio intenso los primeros días",
      "No arrancar la piel que se desprende naturalmente",
    ],
    faq: [
      { q: "¿Qué tipos de peeling ofrece la Dra. Téllez?", a: "La Dra. Téllez trabaja con peelings de ácido glicólico, mandélico, salicílico y TCA (tricloroacético), utilizando marcas de referencia internacional como Sesderma y el protocolo Cosmelan para hiperpigmentación y melasma. La elección del tipo y la profundidad depende siempre del diagnóstico individual." },
      { q: "¿El peeling duele?", a: "Los peelings superficiales generan una leve sensación de ardor o calor que desaparece rápidamente. Los peelings más profundos pueden requerir anestesia tópica y tienen más días de recuperación." },
      { q: "¿Cuándo veré los resultados del peeling?", a: "Los primeros resultados en luminosidad y textura se observan desde la primera sesión. Para manchas y cicatrices, los resultados óptimos se aprecian después de la tercera o cuarta sesión." },
    ],
    relatedServices: ["cosmelan", "laser-co2", "acne"],
    keywords: ["peeling químico bogotá", "peeling acné bogotá", "manchas piel bogotá", "renovación celular bogotá"],
  },
  {
    slug: "retiro-lunares-lipomas",
    title: "Retiro de Lunares y Lipomas",
    shortDescription: "Extirpación segura y precisa de lunares, lipomas y lesiones cutáneas benignas en consultorio. Técnica mínimamente invasiva con mínima cicatriz.",
    description: "El retiro de lunares (nevos) y lipomas es uno de los procedimientos quirúrgicos más frecuentes en dermatología. La Dra. Téllez realiza la extirpación en consultorio con anestesia local, utilizando técnica de cirugía dermatológica para obtener el mejor resultado estético posible y enviando siempre la muestra a estudio histopatológico. El procedimiento es rápido, seguro y no requiere hospitalización.",
    category: "clinica",
    categoryLabel: "Dermatología Clínica",
    duration: "20–45 minutos",
    sessions: "1 sesión",
    priceRange: "Desde $380.000 COP",
    candidates: [
      "Personas con lunares que han cambiado de forma, color o tamaño",
      "Quienes desean retirar un lunar por razones estéticas o porque genera molestia",
      "Pacientes con lipomas (bultos grasos benignos) en cualquier parte del cuerpo",
      "Quienes tienen lesiones cutáneas benignas como quistes sebáceos o fibromas",
      "Personas con antecedentes familiares de melanoma que requieren seguimiento",
    ],
    process: [
      "Consulta y evaluación clínica y dermatoscópica de la lesión",
      "Diagnóstico y decisión conjunta sobre el manejo más adecuado",
      "Aplicación de anestesia local en la zona",
      "Extirpación completa de la lesión con técnica de mínima cicatriz",
      "Cierre de la herida con suturas y apósito",
      "Envío de la muestra a estudio histopatológico",
      "Retiro de puntos y control a los 7–14 días",
    ],
    aftercare: [
      "Mantener la herida limpia y seca según las indicaciones",
      "Cambiar la curación según lo indicado por la Dra. Téllez",
      "Evitar mojar la zona los primeros días",
      "No exponer la cicatriz al sol durante al menos 6 meses",
      "Aplicar protector solar SPF 50+ sobre la cicatriz cuando ya haya cerrado",
      "Asistir al control para el retiro de puntos en la fecha indicada",
    ],
    faq: [
      { q: "¿Es obligatorio enviar el lunar retirado a patología?", a: "Sí. La Dra. Téllez envía todas las lesiones extirpadas a estudio histopatológico, independientemente de su apariencia clínica. Esto garantiza un diagnóstico definitivo y descarta lesiones malignas de forma temprana." },
      { q: "¿Qué tan grande queda la cicatriz?", a: "La cicatriz resultante es proporcional al tamaño de la lesión. La Dra. Téllez utiliza técnicas de cirugía dermatológica para minimizar la cicatriz. Con los cuidados adecuados, especialmente la fotoprotección, la cicatriz tiende a aclararse y volverse imperceptible con el tiempo." },
      { q: "¿Qué es un lipoma y cómo sé si lo que tengo es uno?", a: "Un lipoma es un tumor benigno formado por tejido graso, que se palpa como un bulto blando, móvil y sin dolor debajo de la piel. No es peligroso, pero puede retirarse si molesta, crece o por razones estéticas. La Dra. Téllez confirmará el diagnóstico en consulta." },
      { q: "¿Cuándo debo preocuparme por un lunar?", a: "Usa la regla ABCDE: Asimetría, Borde irregular, Color no uniforme, Diámetro mayor de 6 mm, Evolución (cambio). Si tu lunar cumple alguno de estos criterios, consulta a la brevedad. La detección temprana del melanoma salva vidas." },
    ],
    relatedServices: ["acne", "laser-co2", "peeling-quimico"],
    keywords: ["retiro de lunares bogotá", "extirpación lunar bogotá", "lipoma bogotá", "cirugía dermatológica bogotá", "biopsia lunar bogotá"],
  },
  {
    slug: "sculptra",
    title: "Sculptra",
    shortDescription: "Bioestimulador de colágeno con ácido poli-L-láctico para recuperar volumen facial, mejorar la firmeza y rejuvenecer de forma gradual y natural. Resultados que duran hasta 2 años.",
    description: "Sculptra es un bioestimulador basado en ácido poli-L-láctico (PLLA), un polímero biodegradable que estimula la producción de colágeno propio en la dermis profunda. A diferencia de los fillers convencionales, su efecto es gradual y progresivo: el cuerpo construye nuevo colágeno durante semanas, logrando un resultado completamente natural y de larga duración —hasta 18-24 meses. La Dra. Téllez utiliza Sculptra para recuperar volumen global, mejorar la firmeza y tratar la laxitud moderada, frecuentemente en combinación con ácido hialurónico para resultados completos.",
    category: "estetica",
    categoryLabel: "Dermatología Estética",
    duration: "30–45 minutos por sesión",
    sessions: "2–3 sesiones · intervalo de 4–6 semanas",
    priceRange: "Desde $1.800.000 COP por sesión",
    candidates: [
      "Personas entre 35 y 60 años con pérdida de volumen facial (mejillas, sienes, mandíbula)",
      "Pacientes con laxitud cutánea moderada que prefieren un resultado gradual y natural",
      "Quienes buscan durabilidad: resultados de hasta 2 años sin repetir el tratamiento cada 6 meses",
      "Candidatos a prevención del envejecimiento desde los 35-40 años",
      "Pacientes con arrugas profundas (surco nasogeniano, arrugas de marioneta)",
      "Personas que quieren rejuvenecer cuello, escote o manos",
    ],
    process: [
      "Consulta de evaluación facial: análisis de pérdida de volumen y laxitud",
      "Diseño del plan de sesiones y zonas a tratar",
      "Aplicación de anestesia tópica en las zonas sensibles",
      "Inyección del Sculptra con técnica de aguja o cánula según la zona",
      "Masaje post-procedimiento para distribuir el producto uniformemente",
      "Repetición del protocolo en 2–3 sesiones con intervalo de 4–6 semanas",
    ],
    aftercare: [
      "Aplicar la regla del 5-5-5: masajear la zona 5 minutos, 5 veces al día, durante 5 días",
      "Evitar ejercicio intenso las primeras 24 horas",
      "No sauna ni exposición solar directa por 1 semana",
      "Usar protector solar SPF 50+ todos los días",
      "Los primeros días puede haber algo de volumen por el vehículo acuoso — desaparece en 2–3 días",
      "El resultado real se ve progresivamente entre las 4 y 12 semanas post-sesión",
    ],
    faq: [
      { q: "¿Cuándo se ven los resultados de Sculptra?", a: "Los resultados son graduales. En las primeras 4–6 semanas empieza a notarse la estimulación de colágeno; los resultados plenos se ven entre los 3 y 6 meses. Esta progresividad es precisamente lo que hace que el resultado luzca tan natural." },
      { q: "¿Sculptra es lo mismo que el ácido hialurónico?", a: "No. El ácido hialurónico es un filler de efecto inmediato y reversible. Sculptra es un bioestimulador que activa la producción de colágeno propio: el efecto es gradual y dura hasta 2 años. Se complementan muy bien — muchos pacientes usan ambos en el mismo plan de tratamiento." },
      { q: "¿Qué es la regla del 5-5-5 de Sculptra?", a: "Es el protocolo de masaje post-procedimiento: masajear la zona tratada durante 5 minutos, 5 veces al día, por 5 días. Esto distribuye el producto uniformemente y reduce el riesgo de formación de pequeños nódulos bajo la piel." },
      { q: "¿Sculptra es reversible?", a: "No de forma inmediata como el AH. El PLLA se degrada gradualmente de forma natural a lo largo de los meses. No existe un agente disolvente como la hialuronidasa. Sin embargo, al ser un bioestimulador natural, los efectos adversos son poco frecuentes con la técnica correcta." },
    ],
    relatedServices: ["acido-hialuronico", "toxina-botulinica", "peeling-quimico"],
    keywords: ["sculptra bogotá", "bioestimulador colágeno bogotá", "ácido poliláctico bogotá", "pérdida volumen facial bogotá", "rejuvenecimiento facial bogotá"],
  },
  {
    slug: "cosmelan",
    title: "Cosmelan",
    shortDescription: "Tratamiento despigmentante médico de alta potencia para manchas, melasma e hiperpigmentación post-acné. El protocolo más estudiado del mundo con resultados visibles desde la primera semana.",
    description: "Cosmelan es el tratamiento despigmentante médico de mayor respaldo científico a nivel mundial. Actúa inhibiendo de forma prolongada la enzima tirosinasa para reducir la producción de melanina desde la raíz, tratando de forma efectiva el melasma, las manchas solares, la hiperpigmentación post-inflamatoria (manchas de acné) y el tono irregular de la piel. La Dra. Téllez aplica el protocolo completo en consultorio con seguimiento personalizado durante toda la fase de tratamiento.",
    category: "estetica",
    categoryLabel: "Dermatología Estética",
    duration: "40–60 minutos en consultorio",
    sessions: "1 sesión + mantenimiento en casa",
    priceRange: "$2.100.000 COP",
    candidates: [
      "Personas con melasma (manchas del embarazo, anticonceptivos u hormonales)",
      "Pacientes con manchas solares o daño solar acumulado",
      "Quienes tienen hiperpigmentación post-inflamatoria (manchas de acné)",
      "Pieles con tono irregular o distribución no uniforme del color",
      "Pacientes que han intentado otros tratamientos sin resultados satisfactorios",
      "Todo tipo de fototipos de piel, bajo protocolo ajustado",
    ],
    process: [
      "Consulta de evaluación: diagnóstico del tipo de mancha y condición de la piel",
      "Preparación de la piel 2–4 semanas antes con productos específicos (pre-cosmelan)",
      "Sesión en consultorio: limpieza profunda y aplicación de la mascarilla Cosmelan",
      "Tiempo de acción de la mascarilla: 8–12 horas en casa (según indicación)",
      "Retirada de la mascarilla e inicio del mantenimiento con crema Cosmelan 2",
      "Seguimiento y controles cada 2–4 semanas durante la fase activa",
    ],
    aftercare: [
      "Aplicar crema Cosmelan 2 exactamente según las indicaciones de la Dra. Téllez",
      "Protección solar rigurosa SPF 50+ todos los días, sin excepción",
      "No suspender el tratamiento por enrojecimiento inicial — es parte del proceso",
      "Evitar el sol directo durante todo el tratamiento (mínimo 3 meses)",
      "No usar retinol ni ácidos sin autorización de la Dra. Téllez durante la fase activa",
      "Hidratación intensa y constante de la piel",
    ],
    faq: [
      { q: "¿Cosmelan funciona para el melasma?", a: "Sí. Cosmelan es uno de los tratamientos con mayor evidencia científica para el melasma. Actúa inhibiendo la tirosinasa, la enzima responsable de la producción de melanina, reduciendo las manchas existentes y previniendo su reaparición. Los resultados son progresivos y visibles desde la primera semana." },
      { q: "¿Cuánto tiempo tarda en verse el resultado?", a: "Los primeros resultados en luminosidad y reducción de manchas se observan desde la primera semana. La mejoría máxima se aprecia entre las 4 y 8 semanas de tratamiento. El mantenimiento posterior consolida y prolonga el resultado." },
      { q: "¿El proceso duele o hay mucho tiempo de recuperación?", a: "El procedimiento no es doloroso. Los primeros días después de la aplicación puede haber enrojecimiento, sensibilidad y descamación leve a moderada, que dura entre 3 y 7 días. Después la piel estabiliza y el tratamiento continúa con la crema de mantenimiento en casa." },
      { q: "¿Las manchas vuelven después del Cosmelan?", a: "Sin mantenimiento ni fotoprotección, el melasma puede reaparecer porque tiene un componente hormonal y genético. La Dra. Téllez diseña un protocolo de mantenimiento personalizado para prolongar los resultados y prevenir la reaparición de las manchas." },
    ],
    relatedServices: ["peeling-quimico", "laser-co2", "acne"],
    keywords: ["cosmelan bogotá", "manchas bogotá", "melasma bogotá", "hiperpigmentación bogotá", "tratamiento manchas cara bogotá", "dermatologa manchas bogotá"],
  },
  {
    slug: "depilacion-laser",
    title: "Depilación Láser",
    shortDescription: "Depilación definitiva con láser Triton de Alma — el único equipo con triple longitud de onda simultánea (755 + 810 + 1064 nm). Actúa en todos los fototipos de piel, incluyendo piel morena, con mínima molestia y resultados permanentes.",
    description: "En el consultorio utilizamos el láser Triton de Alma Lasers, considerado el estándar de oro en depilación definitiva. Su ventaja principal frente a otros equipos es la tecnología de triple longitud de onda simultánea: emite al mismo tiempo las longitudes de 755 nm (Alexandrita), 810 nm (Diodo) y 1064 nm (Nd:YAG), lo que permite tratar de forma efectiva cualquier tipo de pelo —fino, grueso, claro u oscuro— y cualquier fototipo de piel, desde la más clara hasta la más oscura. La tecnología In-Motion del Triton desliza el cabezal en movimiento continuo sobre la piel, cubriendo áreas grandes en menos tiempo y con mayor comodidad que los láseres convencionales. El sistema de enfriamiento integrado por zafiro protege la superficie de la piel durante el disparo, reduciendo al mínimo la molestia. El resultado: una reducción permanente del pelo desde las primeras sesiones, segura y adaptada a cada paciente.",
    category: "laser",
    categoryLabel: "Tecnología Láser",
    duration: "15–60 minutos según la zona",
    sessions: "6–8 sesiones recomendadas",
    priceRange: "Desde $200.000 COP por zona",
    candidates: [
      "Personas que desean eliminar el pelo de forma permanente en cualquier zona del cuerpo",
      "Pacientes con piel morena u oscura (fototipos IV–VI) que otros láseres no pueden tratar con seguridad",
      "Quienes tienen pelo fino o claro que sistemas convencionales no detectan bien",
      "Personas con foliculitis, irritación o ingrown hairs recurrentes por rasurado o cera",
      "Quienes buscan resultados rápidos: el Triton cubre zonas grandes en la mitad del tiempo",
    ],
    process: [
      "Consulta inicial: evaluación del fototipo de piel y características del pelo",
      "Indicaciones previas: rasurar la zona 24 horas antes, sin sol ni autobronceadores recientes",
      "Aplicación de gel conductor para optimizar la conducción del láser",
      "Tratamiento con Triton en modalidad In-Motion: cabezal deslizante sobre la zona",
      "Aplicación de crema calmante post-procedimiento",
      "Programación de las siguientes sesiones según el ciclo de crecimiento del pelo",
    ],
    aftercare: [
      "Evitar la exposición solar directa en la zona tratada durante 2 semanas",
      "Usar protector solar SPF 50+ si la zona queda expuesta al sol",
      "No depilarse con cera ni pinzas entre sesiones — solo rasurado si es necesario",
      "Evitar el calor excesivo (sauna, jacuzzi) las primeras 24–48 horas",
      "Aplicar crema hidratante o calmante si hay sensibilidad en la zona",
      "No exfoliar la zona tratada los primeros 5 días",
    ],
    faq: [
      { q: "¿Por qué el láser Triton es mejor que otros equipos?", a: "La mayoría de los láseres de depilación trabajan con una sola longitud de onda: o Alexandrita (eficaz en piel clara), o Diodo (intermedio), o Nd:YAG (piel oscura). El Triton dispara las tres simultáneamente, lo que significa que ningún tipo de pelo ni fototipo queda sin cobertura. Además, su sistema In-Motion es más rápido y su enfriamiento integrado lo hace más cómodo." },
      { q: "¿Funciona en piel morena u oscura?", a: "Sí. Gracias a la longitud de onda de 1064 nm (Nd:YAG) incluida en el Triton, el equipo es completamente seguro y eficaz en fototipos IV, V y VI. Muchos otros láseres no recomiendan estos fototipos por riesgo de quemaduras — con el Triton ese riesgo se minimiza." },
      { q: "¿Cuántas sesiones necesito?", a: "Se recomiendan entre 6 y 8 sesiones espaciadas cada 4–8 semanas, dependiendo de la zona y el tipo de pelo. Después del ciclo completo, el pelo restante es significativamente más fino y escaso. Pueden requerirse sesiones de mantenimiento anuales." },
      { q: "¿Duele la depilación con Triton?", a: "Es uno de los láseres más cómodos del mercado gracias al sistema de enfriamiento por zafiro integrado y la tecnología In-Motion. La mayoría de los pacientes describe solo una leve sensación de calor. En zonas muy sensibles se puede aplicar crema anestésica tópica." },
    ],
    relatedServices: ["laser-co2", "peeling-quimico"],
    keywords: ["depilación láser bogotá", "laser triton bogotá", "alma triton bogotá", "depilación definitiva bogotá", "laser hair removal bogotá", "depilación piel morena bogotá"],
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export function getServicesByCategory(category: Service["category"]): Service[] {
  return services.filter((s) => s.category === category);
}
